### ISSUE TITLE
kolom development di pengisian profile.md

### ISSUE THREAD

**Issue by daimessdn** [mfaisaal/basicvalidation#14]
Selamat malam...

Punten, ingin bertanya...

Untuk pengisian **development** di markdown yg `profiles` itu teh bisa dijelasin maksudnya itu teh ngisinya gimana?

Nuhun...

**Comment by zycamichaela** [comment]
Silahkan diisi dengan apa yang sedang dikembangkan sekarang.
Terima Kasih.
